server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/try?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: luiyuXUAN720
